---
- name: Check checksum
  become: yes
  hosts: localhost

  vars:

    jenkins_host:  http://${jenkins-test_public_ip}:8080/job/cicd/lastStableBuild/api/json?tree=artifacts%5BrelativePath%5D
    jenkins_user: ${login}
    jenkins_password: ${password}
    whl_test_dest: /ansible-cicd/test/{{ lookup('file', 'filename_test.txt') }}
    whl_dest: /ansible-cicd/{{ lookup('file', 'filename.txt') }}


  tasks:

    - name: Make test dir
      file:
        path: /ansible-cicd/test
        state: directory


    - name: Get url
      uri:
        url: "{{ jenkins_host }}"
        user: "{{ jenkins_user }}"
        password: "{{ jenkins_password }}"
        method: GET
        force_basic_auth: yes
      register: list_artifact

    - name: Write all data in json
      copy:
        content="{{ list_artifact }}"
        dest=/ansible-cicd/files/list_test_artifacts.json


    - name: Get path and filename
      shell: |
        grep -oE "[0-9]+/+[a-zA-Z0-9_.-]+.whl" /ansible-cicd/files/list_test_artifacts.json | awk '!a[$0]++' > /ansible-cicd/files/path_test.txt


    - name: Get whl filename
      shell: |
        grep -oE "[a-zA-Z0-9_.-]+.whl" /ansible-cicd/files/path_test.txt | awk '!a[$0]++' > /ansible-cicd/files/filename_test.txt


    - name: Install wheel package
      shell: |
        cd /ansible-cicd/test/
        pip3 install "{{ lookup('file', 'filename_test.txt') }}"


    - name: Get checksum of test file
      stat:
        path: "{{ whl_test_dest }}"
      register: test_file


    - name: Get checksum of existing file
      stat:
        path: "{{ whl_dest }}"
      register: exist_file


    - name: Test  SHA
      shell: |
        if [ $exist_file -eq $test_file ]
        then
          echo "True"
        else
          echo "False"
        fi
      register: result


    - name: Debug
      debug:
         var: result


    - block:

        - name: Comparing if equal
          shell: |
            cd /ansible-cicd
            sudo rm -r test

      when: result == True


    - block:

        - name: Comparing if not equal
          shell: |
            cd /ansible-cicd
            sudo rm "{ lookup('file', 'filename.txt') }}"
            cd /ansible-cicd/test
            mv "{{ lookup('file', 'filename_test.txt') }}" /ansible-cicd

      when: result == False