---
- name: Installation
  become: yes
  hosts:  localhost

  tasks:

  - name: Install python
    raw: apt-get update && apt-get install -y python3


  - name: Install  pip
    apt:
      name:
        - python3-pip


  - name: Install some python3 global deps
    pip:
      name:
        - packaging
        - appdirs
      state: latest
      executable: pip3


  - name: Install python3 dependencies
    pip:
      name:
        - wheel
        - setuptools
      executable: pip3
      state: latest


- name: Checking
  become: yes
  hosts: localhost

  vars:
    whl_dest: /ansible-cicd/elevator_task-0.0.1-py3-none-any.whl

  tasks:
    - name: Check if .whl exist in this folder
      stat:
        path: "{{ whl_dest }}"
      register: file_details

    - block:

        - name: File doesn't exist
          command: ansible-playbook playbook2.yml

      when: not file_details.stat.exists
      
    - block:

        - name: File exist
          command: ansible-playbook playbook1.yml
      when: file_details.stat.exists