---

- name: Deploying
  become: yes
  hosts: localhost

  vars:
    jenkins_host:  http://${jenkins-test_public_ip}:8080/job/cicd/lastSuccessfulBuild/api/json?tree=artifacts%5BrelativePath$
    jenkins_user: ${login}
    jenkins_password: ${password}
    whl_dest: /ansible-cicd/"{{ latest_artifact }}"

  tasks:
    - name: Intsall url
      uri:
        url: "{{ jenkins_host }}"
        user: "{{ jenkins_user }}"
        password: "{{ jenkins_password }}"
        dest: "{{ whl_dest }}"
        method: GET
        force_basic_auth: yes
        return_content: yes
      register: list_artifact

    - name: Write in json
      copy:
        content="{{ list_artifact }}"
        dest=/ansible-cicd/list.json

    - name: Get list
      shell: |
        grep -oE "[0-9]+/+[a-zA-Z0-9_.-]+.whl" list.json | awk '!a[$0]++' > list.txt
      register: latest_artifact

    - name: Install wheel package
      command: pip3 install "{{ latest_artifact }}"
