---

- name: Deploying
  become: yes
  hosts: localhost

  vars:
    jenkins_host: http://${jenkins-test_public_ip}:8080/job/cicd/lastSuccessfulBuild/artifact/dist/elevator_task-0.0.1-py3-none-any.whl
    jenkins_user: ${login}
    jenkins_password: ${password}
    whl_dest: /ansible/elevator_task-0.0.1-py3-none-any.whl

  tasks:
    - name: Intsall url
      uri:
        url: "{{ jenkins_host }}"
        user: "{{ jenkins_user }}"
        password: "{{ jenkins_password }}"
        dest: "{{ whl_dest }}"
        method: GET
        force_basic_auth: yes
        return_content: yes

    - name: Install wheel package
      command: pip3 install elevator_task-0.0.1-py3-none-any.whl
