---
- name: Install needed packages
  become: yes
  hosts:  localhost


  tasks:


  - name: Install python
    raw: apt-get update && apt-get install -y python3


  - name: Install  pip
    apt:
      name:
        - python3-pip


  - name: Install some python3 global deps
    pip:
      name:
        - packaging
        - appdirs
      state: latest
      executable: pip3


  - name: Install python3 dependencies
    pip:
      name:
        - wheel
        - setuptools
      executable: pip3
      state: latest



- name: File checking
  become: yes
  hosts: localhost


  vars:
    jenkins_host:  http://${jenkins-test_public_ip}:8080/job/cicd/lastStableBuild/api/json?tree=artifacts%5BrelativePath%5D
    jenkins_user: ${login}
    jenkins_password: ${password}


  tasks:


    - name: Make dir for all txt/json files
      file:
        path: /ansible-cicd/files
        state: directory


    - name: Get url response
      uri:
        url: "{{ jenkins_host }}"
        user: "{{ jenkins_user }}"
        password: "{{ jenkins_password }}"
        method: GET
        force_basic_auth: yes
      register: pl_list_artifacts


    - name: Write all data in json
      copy:
        content="{{ pl_list_artifacts }}"
        dest=/ansible-cicd/files/pl_list_artifacts.json


    - name: Get path and filename
      shell: |
        grep -oE "[0-9]+/+[a-zA-Z0-9_.-]+.whl" /ansible-cicd/files/pl_list_artifacts.json | awk '!a[$0]++' > /ansible-cicd/files/pl_path.txt


    - name: Get whl filename
      shell: |
        grep -oE "[a-zA-Z0-9_.-]+.whl" /ansible-cicd/files/pl_path.txt | awk '!a[$0]++' > /ansible-cicd/files/pl_filename.txt


    - name: Check if any .whl file exist
      shell: |
        if ls /ansible-cicd/*.whl 1>/dev/null 2>&1
        then
          echo "Exist"
        fi
      register: file_result
      

    - name: Debug
      debug:
        var: file_result


    - block:

        - name: File doesn't exist
          command: ansible-playbook playbook2.yml

      when: file_result.stdout != "Exist"


    - block:

        - name: File exist
          command: ansible-playbook playbook1.yml

      when: file_result.stdout == "Exist"