---
- name: Check checksum
  become: yes
  hosts: localhost

  vars:

    jenkins_host:  http://${jenkins-test_public_ip}:8080/job/cicd/lastStableBuild/api/json?tree=artifacts%5BrelativePath%5D
    jenkins_user: ${login}
    jenkins_password: ${password}
    whl_test_dest: /ansible-cicd/test/
    whl_dest: /ansible-cicd/


  tasks:

    - name: Make test dir
      file:
        path: /ansible-cicd/test
        state: directory


    - name: Get url
      uri:
        url: "{{ jenkins_host }}"
        user: "{{ jenkins_user }}"
        password: "{{ jenkins_password }}"
        method: GET
        force_basic_auth: yes
      register: list_artifact


    - name: Write all data in json
      copy:
        content="{{ list_artifact }}"
        dest=/ansible-cicd/files/list_artifacts.json


    - name: Get path and filename
      shell: |
        grep -oE "[0-9]+/+[a-zA-Z0-9_.-]+.whl" /ansible-cicd/files/list_artifacts.json | awk '!a[$0]++' > /ansible-cicd/files/path.txt


    - name: Get whl filename
      shell: |
        grep -oE "[a-zA-Z0-9_.-]+.whl" /ansible-cicd/files/path.txt | awk '!a[$0]++' > /ansible-cicd/files/filename.txt


    - name: Install wheel package
      shell: |
        cd /ansible-cicd/
        pip3 install "{{ lookup('file', 'filename.txt') }}"


    - name: Get checksum of test file
      stat:
        path: "/ansible-cicd/test/{{ lookup('file', 'filename.txt') }}"
        checksum: sha1
        get_checksum: yes
      register: test_file_checksum


    - name: Test SHA
      set_fact:
         testsha1: "{{ test_file_checksum.stat.checksum }}"


    - name: Get checksum of existing file
      stat:
        path: "/ansible-cicd/{{ lookup('file', 'filename.txt') }}"
        checksum: sha1
        get_checksum: yes
      register: exist_file_checksum


    - name: Exist SHA
      set_fact:
        existsha1: "{{ exist_file_checksum.stat.checksum }}"


    - name: Comparing if equal
      when: testsha1 == existsha1
      shell: |
        cd /ansible-cicd
        sudo rm -r test


    - name: Comparing if not equal
      when: testsha1 != existsha1
      shell: |
        cd /ansible-cicd
        sudo rm "{ lookup('file', 'filename.txt') }}"
        cd /ansible-cicd/test
        mv "{{ lookup('file', 'filename.txt') }}" /ansible-cicd